### ISSUE TITLE
[Feature] 채팅방 생성 API 추가

### ISSUE THREAD

**Issue by jwooo** [team-urbanlife/back-end#23]
## 📑 작업 사항
채팅방 생성 API 추가

## To-do
- [x] 채팅방 생성 API 추가
- [x] 채팅방 생성 API 테스트 작성
- [x] 채팅방 생성 API Docs 작성

## ETC
