### ISSUE TITLE
[Deploy] 빌드 자동화 설정

### ISSUE THREAD

**Issue by jwooo** [team-urbanlife/back-end#5]
## 📑 작업 사항
빌드 자동화 설정

## To-do
- [x] yaml 파일 설정
- [x] docker 파일 작성
- [x] 깃허브 액션 워크플로우 작성

## ETC

**Comment by AHNYUNKI** [comment]
빌드 자동화 설정 하시면서 JaCoCo 테스트 커버리지 분석 설정도 추가 가능하실까요?
