### ISSUE TITLE
[Feature] 사용자 동행 게시글 조회 API 구현

### ISSUE THREAD

**Issue by jwooo** [team-urbanlife/back-end#70]
## 📑 작업 사항
- 사용자 동행 게시글 조회 API 구현

## To-do
- [x] 샤용자 동행 게시글 조회 API 추가
- [x] 사용자 동행 게시글 조회 API 테스트 추가
- [x] 사용자 동행 게시글 조회 API Docs 추가

## ETC
