### ISSUE TITLE
[Feature] 사용자 일정 조회 API 구현

### ISSUE THREAD

**Issue by jwooo** [team-urbanlife/back-end#82]
## 📑 작업 사항
- 사용자 일정 조회 API 구현

## To-do
- [ ] 사용자 일정 조회 API 구현
- [ ] 사용자 일정 조회 API 테스트 추가
- [ ] 사용자 일정 조회 API Docs 추가

## ETC
