### ISSUE TITLE
[Feature] 좋아요 게시글 조회 API 구현

### ISSUE THREAD

**Issue by jwooo** [team-urbanlife/back-end#84]
## 📑 작업 사항
- 좋아요한 게시글 조회 API 구현

## To-do
- [x] 좋아요한 게시글 조회 API 구현
- [x] 좋아요한 게시글 조회 API 테스트 추가
- [x] 좋아요한 게시글 조회 API Docs 추가

## ETC
