### ISSUE TITLE
[Feature] 사용자 정보 조회 API 구현

### ISSUE THREAD

**Issue by jwooo** [team-urbanlife/back-end#86]
## 📑 작업 사항
- 사용자 정보 조회 API 구현

## To-do
- [x] 사용자 정보 조회 API 추가
- [x] 사용자 정보 조회 API 테스트 추가
- [x] 사용자 정보 조회 API Docs 추가

## ETC
