### ISSUE TITLE
[Feature] Schedule 수정 API 구현

### ISSUE THREAD

**Issue by AHNYUNKI** [team-urbanlife/back-end#9]
## 📑 작업 사항
Schedule 수정 API 구현

## To-do
- [x] Schedule 수정 API 구현
- [x] Schedule 수정 API 테스트 코드 작성
- [x] DetailedPlan 수정 API 구현
- [x] DetailedPlan 수정 API 테스트 코드 작성

## ETC
사용자가 일정을 생성하면 일정 그룹에 포함되어 있는 사람이면 누구든 같이 수정할 수 있게 구현해야합니다. (일정 초대 관련 API는 일정 관리 API가 전부 구현 되면 작업할 예정)
